/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 5.0 */
public interface CalculatorTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTTYPE = 5;
  public int JJTSTATEMENT = 6;
  public int JJTVOID = 7;
  public int JJTAND = 8;
  public int JJTLESS = 9;
  public int JJTPLUS = 10;
  public int JJTMINUS = 11;
  public int JJTMULT = 12;
  public int JJTTERMINAL = 13;
  public int JJTTERMINALALTERNATIVE = 14;


  public String[] jjtNodeName = {
    "Program",
    "ImportDeclaration",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "Type",
    "Statement",
    "void",
    "And",
    "Less",
    "Plus",
    "Minus",
    "Mult",
    "Terminal",
    "TerminalAlternative",
  };
}
/* JavaCC - OriginalChecksum=b877c79d2c02e0bd8018ada7ea1c8eef (do not edit this line) */
