/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTIMPORTDECLARATION = 1;
  public int JJTCLASSDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMETHODDECLARATION = 4;
  public int JJTTYPE = 5;
  public int JJTSTATEMENT = 6;
  public int JJTEXPRESSION = 7;
  public int JJTEXPRESSION1 = 8;
  public int JJTIDENTIFIER = 9;
  public int JJTINTEGERLITERAL = 10;


  public String[] jjtNodeName = {
    "Program",
    "ImportDeclaration",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "Type",
    "Statement",
    "Expression",
    "Expression1",
    "Identifier",
    "IntegerLiteral",
  };
}
/* JavaCC - OriginalChecksum=d81847f8404b5125d63ba58f7ed94d2d (do not edit this line) */
